version: '3'

services:
  ros-master:
    image: ghcr.io/remyrobotics/robotics-test:latest
    command: stdbuf -o L roscore
    network_mode: host

  gazebo:
    image: ghcr.io/remyrobotics/robotics-test:latest
    depends_on:
      - ros-master
    network_mode: host
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "XAUTHORITYS"
      - "DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - "/dev/dri/"
    command: bash -c "cd /home/catkin_ws && source devel/setup.bash && roslaunch --wait simple_scene gazebo.launch"
    runtime: nvidia
